In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
import tensorflow as tf

In [2]:
df=pd.read_csv("Churn Dataset.csv")
df=pd.DataFrame(df)
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [3]:
df.shape

(7043, 21)

In [4]:
df.Churn.replace(["Yes", "No"], [1, 0], inplace= True)

In [20]:
df.isna().sum()

SeniorCitizen            0
tenure                   0
MonthlyCharges           0
Churn                    0
customerID_0002-ORFBO    0
                        ..
TotalCharges_997.75      0
TotalCharges_998.1       0
TotalCharges_999.45      0
TotalCharges_999.8       0
TotalCharges_999.9       0
Length: 13619, dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   int64
dtypes: float64(1), int64(3), object(17)
memory usage: 1.1+ MB

In [21]:
df=pd.get_dummies(df)

In [8]:
x=df.drop(columns=['Churn'])
y=df['Churn']
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [9]:
x_train.head()

,SeniorCitizen,tenure,MonthlyCharges,customerID_0002-ORFBO,customerID_0003-MKNFE,customerID_0004-TLHLJ,customerID_0011-IGKFF,customerID_0013-EXCHZ,customerID_0013-MHZWF,customerID_0013-SMEOE,...,TotalCharges_995.35,TotalCharges_996.45,TotalCharges_996.85,TotalCharges_996.95,TotalCharges_997.65,TotalCharges_997.75,TotalCharges_998.1,TotalCharges_999.45,TotalCharges_999.8,TotalCharges_999.9
2142,0,21,64.85,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1623,0,54,97.20,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6074,0,1,23.45,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1362,0,4,70.20,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6754,0,0,61.90,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
y_train.head()

2142    0
1623    0
6074    1
1362    1
6754    0
Name: Churn, dtype: int64

In [11]:
from tensorflow.keras.models import Sequential, load_model
from tensorflow.keras.layers import Dense
from sklearn.metrics import accuracy_score

In [12]:
model = Sequential()
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [13]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [14]:
model.fit(x_train, y_train, epochs=50, batch_size=10)

Epoch 1/50
564/564 [==============================] - 5s 5ms/step - loss: 0.4943 - accuracy: 0.7735
Epoch 2/50
564/564 [==============================] - 2s 4ms/step - loss: 0.4270 - accuracy: 0.8040
Epoch 3/50
564/564 [==============================] - 2s 4ms/step - loss: 0.4101 - accuracy: 0.8101
Epoch 4/50
564/564 [==============================] - 3s 5ms/step - loss: 0.3930 - accuracy: 0.8195
Epoch 5/50
564/564 [==============================] - 3s 4ms/step - loss: 0.3707 - accuracy: 0.8353
Epoch 6/50
564/564 [==============================] - 2s 4ms/step - loss: 0.3274 - accuracy: 0.8632
Epoch 7/50
564/564 [==============================] - 2s 4ms/step - loss: 0.2609 - accuracy: 0.9129
Epoch 8/50
564/564 [==============================] - 2s 4ms/step - loss: 0.1770 - accuracy: 0.9634
Epoch 9/50
564/564 [==============================] - 3s 4ms/step - loss: 0.1027 - accuracy: 0.9886
Epoch 10/50
564/564 [==============================] - 2s 4ms/step - loss: 0.0533 - accuracy: 0.9975
Epoch 11/50
564/564 [==============================] - 2s 4ms/step - loss: 0.0295 - accuracy: 0.9996
Epoch 12/50
564/564 [==============================] - 2s 4ms/step - loss: 0.0166 - accuracy: 1.0000
Epoch 13/50
564/564 [==============================] - 2s 4ms/step - loss: 0.0100 - accuracy: 1.0000
Epoch 14/50
564/564 [==============================] - 2s 4ms/step - loss: 0.0064 - accuracy: 1.0000
Epoch 15/50
564/564 [==============================] - 3s 5ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 16/50
564/564 [==============================] - 2s 4ms/step - loss: 0.0028 - accuracy: 1.0000
Epoch 17/50
564/564 [==============================] - 2s 4ms/step - loss: 0.0019 - accuracy: 1.0000
Epoch 18/50
564/564 [==============================] - 3s 4ms/step - loss: 0.0013 - accuracy: 1.0000
Epoch 19/50
564/564 [==============================] - 2s 4ms/step - loss: 9.0546e-04 - accuracy: 1.0000
Epoch 20/50
564/564 [==============================] - 2s 4ms/step - loss: 6.2451e-04 - accuracy: 1.0000
Epoch 21/50
564/564 [==============================] - 2s 4ms/step - loss: 4.4358e-04 - accuracy: 1.0000
Epoch 22/50
564/564 [==============================] - 2s 4ms/step - loss: 3.1909e-04 - accuracy: 1.0000
Epoch 23/50
564/564 [==============================] - 2s 4ms/step - loss: 2.1956e-04 - accuracy: 1.0000
Epoch 24/50
564/564 [==============================] - 2s 4ms/step - loss: 1.5365e-04 - accuracy: 1.0000
Epoch 25/50
564/564 [==============================] - 2s 4ms/step - loss: 1.1257e-04 - accuracy: 1.0000
Epoch 26/50
564/564 [==============================] - 2s 4ms/step - loss: 7.7424e-05 - accuracy: 1.0000
Epoch 27/50
564/564 [==============================] - 2s 4ms/step - loss: 5.8820e-05 - accuracy: 1.0000
Epoch 28/50
564/564 [==============================] - 2s 4ms/step - loss: 4.0526e-05 - accuracy: 1.0000
Epoch 29/50
564/564 [==============================] - 2s 4ms/step - loss: 2.9706e-05 - accuracy: 1.0000
Epoch 30/50
564/564 [==============================] - 3s 5ms/step - loss: 2.2366e-05 - accuracy: 1.0000
Epoch 31/50
564/564 [==============================] - 2s 4ms/step - loss: 1.5355e-05 - accuracy: 1.0000
Epoch 32/50
564/564 [==============================] - 3s 5ms/step - loss: 1.1393e-05 - accuracy: 1.0000
Epoch 33/50
564/564 [==============================] - 2s 4ms/step - loss: 8.0879e-06 - accuracy: 1.0000
Epoch 34/50
564/564 [==============================] - 2s 4ms/step - loss: 5.9914e-06 - accuracy: 1.0000
Epoch 35/50
564/564 [==============================] - 2s 4ms/step - loss: 4.4027e-06 - accuracy: 1.0000
Epoch 36/50
564/564 [==============================] - 2s 4ms/step - loss: 3.1508e-06 - accuracy: 1.0000
Epoch 37/50
564/564 [==============================] - 2s 4ms/step - loss: 2.3765e-06 - accuracy: 1.0000
Epoch 38/50
564/564 [==============================] - 3s 5ms/step - loss: 1.6860e-06 - accuracy: 1.0000
Epoch 39/50
564/564 [==============================] - 3s 5ms/step - loss: 1.2524e-06 - accuracy: 1.0000
Epoch 40/50
564/564 [==============================] - 3s 4ms/step - loss: 9.2814e-07 - accuracy: 1.0000
Epoch 41/50
564/564 [==============================] - 2s 4ms/step - loss: 6.6877e-07 - accuracy: 1.0000
Epoch 42/50
564/564 [==============================] - 2s 4ms/step - loss: 4.9700e-07 - accuracy: 1.0000
Epoch 43/50
564/564 [==============================] - 2s 4ms/step - loss: 3.6867e-07 - accuracy: 1.0000
Epoch 44/50
564/564 [==============================] - 2s 4ms/step - loss: 2.6720e-07 - accuracy: 1.0000
Epoch 45/50
564/564 [==============================] - 3s 5ms/step - loss: 2.0269e-07 - accuracy: 1.0000
Epoch 46/50
564/564 [==============================] - 2s 4ms/step - loss: 1.5109e-07 - accuracy: 1.0000
Epoch 47/50
564/564 [==============================] - 2s 4ms/step - loss: 1.1156e-07 - accuracy: 1.0000
Epoch 48/50
564/564 [==============================] - 2s 4ms/step - loss: 8.2847e-08 - accuracy: 1.0000
Epoch 49/50
564/564 [==============================] - 3s 5ms/step - loss: 6.4230e-08 - accuracy: 1.0000
Epoch 50/50
564/564 [==============================] - 2s 4ms/step - loss: 4.8291e-08 - accuracy: 1.0000

In [15]:
y_hat=model.predict(x_test)
y_hat={ 0 if val<0 else 1 for val in y_hat  }

45/45 [==============================] - 0s 4ms/step

In [16]:
accuracy_score= model.evaluate(x_test, y_test)

45/45 [==============================] - 0s 4ms/step - loss: 0.7212 - accuracy: 0.7743